package kosmicbor.moviesagain.domain.usecases.screenusecases

import kosmicbor.moviesagain.domain.usecases.methodsusecases.GetMovieDescriptionUseCase

interface MovieDescriptionScreenUseCase: GetMovieDescriptionUseCase {
}